# Generated by Django 2.0.4 on 2018-05-10 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='importance',
            field=models.IntegerField(choices=[(0, 'white'), (100, 'green'), (200, 'orange'), (300, 'red')], default=100),
        ),
    ]
